# Generated by Django 4.1.1 on 2022-12-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
